services:
  gateway-service:
    env_file:
      - ./gateway-service/.env
    build:
      context: ./gateway-service
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./gateway-service
    #       target: /code
    ports:
      - 7001:80
    networks:
      - shrp
    depends_on:
      - tasks-service
      - auth-service

  tasks-service:
    env_file:
      - ./tasks-service/.env
    build:
      context: ./tasks-service
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./tasks-service
    #       target: /code
    ports:
      - 8000:80
    networks:
      - shrp
    depends_on:
      tasks-db:
        condition: service_healthy

  tasks-db:
    image: mongo:5.0
    env_file:
      - ./tasks-db/.env
    volumes:
      - ./tasks-db/mongoDB:/docker-entrypoint-initdb.d
    ports:
      - 27018:27017
    networks:
      - shrp
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    env_file:
      - ./auth-service/.env
    build:
      context: ./auth-service
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./auth
    #       target: /code
    ports:
      - 9000:80
    networks:
      - shrp
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: mongo:5.0
    env_file:
      - ./auth-db/.env
    volumes:
      - ./auth-db/mongoDB:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - shrp
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./rabbitmq/.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - shrp

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=tasks-db
    ports:
      - 8080:8080
    networks:
      - shrp

networks:
  shrp:
    driver: bridge
